name: sarif

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: action.sarif
